version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-api
    restart: always
    env_file: .env
    environment:
      - DB_URI=$DB_URI
      - SECRET_KEY=$SECRET_KEY
    ports:
      - '80:5000'