version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-api
    restart: always
    env_file: .env
    environment:
      - DB_URI=$DB_URI
    ports:
      - '80:5000'
    depends_on:
      - db
  
  db:
    image: mongo:4.1.8-xenial
    restart: always
    env_file: .env
    environment:
      - DB_URI=$DB_URI