version: '3'
services:
  app:
    container_name: notes-api-dev
    restart: always
    env_file: .env
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DB_URI=$DB_URI
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - '5000:5000'
    depends_on:
      - db

  db:
    image: mongo:4.1.8-xenial
    restart: always
    ports:
    - "27017:27017"
    volumes:
      - './server:/home/node/app/server'